# -*- coding: utf-8 -*-
"""first assingment .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rrlqfdxOdsyVMBMyY6LiNFCged-84K7q
"""



"""#basic python

#1. what is python, and why is it popular

ANS- Python is a high-level, easy-to-read programming language created by Guido van Rossam. Its popular because its syntax is super clean almost like English, it has tons of libraries for everything — web, data science, automation, ML — and the community is massive, so you get help instantly.

#2.what is an interpreter in python?

ANS- The interpreter is the thing that runs Python code line by line instead of compiling everything first. cpython is the default one we all use.

#3.what are pre-defined keywords in python

ANS-Pre-defined keywords are reserved words that Python already uses for its own syntax, like if, else, for, while, class, True, False, None, and, or, return, etc. You can see the full list with import keyword followed by keyword.

#4.can keywords be used as variable names?

ANS-No you can’t use them as variable names. If you try something like True = 10, Python will throw SyntaxError.

#5. what is mutability in python?

ANS-Mutability means whether you can change the content of an object after creating it. Lists, dictionaries, sets → mutable. Strings, tuples, numbers → immutable.

#6.why are lists mutable but tuples are immutable?

ans- Lists are made to be changed anytime — add, remove, modify items. Tuples are fixed on purpose so they can be used as dictionary keys and in sets, plus they are faster and safer when you don’t want accidental changes.

#7.what is the difference between "==" and "is" operators in python?

ANS-  == checks if the values are equal. “is” checks if both variables point to the exact same object in memory. Example: a = [1,2,3]; b = [1,2,3] → a == b is True, but a is b is False.

#8.what are the logical operators in python?

ANS- The three logical operators are and, or, not. They work on truth values and also do short-circuiting (stops checking further if result is already decided).

#9. what is the casting in python ?

ans- Type casting is converting one data type into another, like int(“5”), float(10), str(100), list(“hello”) etc.

#10. what is the difference between implicit and explicit type casting?

ans- Implicit → Python does it automatically (5 + 3.0 becomes 8.0). Explicit → we force it using functions like int(), float(), etc.

#11. what is the purpose of conditional  statement in python?

ans. Conditional statements (if, elif, else) let the program decide which block of code to run depending on whether a condition is True or False.

#12. how does the elif statement work?

ans. elif is checked only if the if above it (and all previous elifs) are False. It basically means “else if”.

#13.what is the difference between for and while loops?

ans- for loop is used when you know how many times you want to run (like looping over a list or range). while loop runs as long as a condition stays True — you don’t need to know the count beforehand.

#14.describe a senerio where a while loop is more suitable than a for loop

ans-A common case is asking the user for a correct password. You don’t know how many attempts they’ll take, so you keep looping with while until they enter the right one.

# PRACTICAL QUESTIONS

#1. white a PYTHON program to print "hello,world"
"""

print("hello world")

"""#2.write a python program that displays your name and age."""

name = "kabir"
age = 23
print(f"my name is {name} and I am {age} years old.")

"""#3.white code to print all the pre defined keywords in python using the keyword library."""

import keyword
print(keyword.kwlist)

"""#4. write a program that checks if a given word is a python keywords"""

print(help('keywords'))

"""#5.create a list and tuple in python,and demostrate how attemppting how attempting to change an element works diffently for each"""

_list = [40,88,93]
_tuple = (40, 88, 93)
# Changing an element in the list
_list[1] = 12
print("List is updated:", _list)
# Trying to change an element in the tuple
try:
    _tuple[1] = 70
except TypeError:
    print("Error: Tuples do not change because (immutable).")

"""#6.Write a function to demonstrate the behavior of mutable and immutable arguments.

"""

# Function to modify the value
def modify(value):
    print("Before modification:", value)

    # If it's a list (mutable), modify it
    if isinstance(value, list):
        value[0] = "CHANGED"

    # If it's an integer (immutable), try to modify it
    if isinstance(value, int):
        value = value + 10
        print("Inside function (after change):", value)

    print("After modification:", value)


# Main program
# Immutable example
num = 50
print("IMMUTABLE EXAMPLE:")
modify(num)
print("Outside function:", num)

print("\n---------------------------\n")

# Mutable example
my_list = [10, 20, 30]
print("MUTABLE EXAMPLE:")
modify(my_list)
print("Outside function:", my_list)

"""#7.Write a program that performs basic arithmetic operations on two user-input numbers.

"""

# Program to perform basic arithmetic operations on two numbers

# Taking input from the user
num1 = float(input("Enter first number: "))   # Example: 12
num2 = float(input("Enter second number: "))  # Example: 4

# Performing arithmetic operations
addition = num1 + num2
subtraction = num1 - num2
multiplication = num1 * num2

# Checking division condition (cannot divide by zero)
if num2 != 0:
    division = num1 / num2
else:
    division = "Error: Division by zero is not allowed"

# Displaying the results
print("\n--- Results ---")
print("First Number:", num1)
print("Second Number:", num2)
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

"""#8.Write a program to demonstrate the use of logical operators."""

# Program to demonstrate logical operators in Python

# Taking two values
a = True
b = False

print("Value of a:", a)
print("Value of b:", b)

# Using logical AND
and_result = a and b

# Using logical OR
or_result = a or b

# Using logical NOT
not_result = not a

# Displaying results
print("\n--- Logical Operations ---")
print("a AND b:", and_result)
print("a OR b:", or_result)
print("NOT a:", not_result)

"""#9.Write a Python program to convert user input from string to integer, float, and boolean types.

"""

# Program to convert user input to integer, float, and boolean types

# Taking input from the user (input is always a string)
user_input = input("Enter a value: ")

print("\nOriginal Input (as string):", user_input)

# Converting to integer
try:
    int_value = int(user_input)
except ValueError:
    int_value = "Cannot convert to integer"

# Converting to float
try:
    float_value = float(user_input)
except ValueError:
    float_value = "Cannot convert to float"

# Converting to boolean
# In Python: empty string = False, any non-empty string = True
bool_value = bool(user_input)

# Displaying results
print("\n--- Converted Values ---")
print("As Integer:", int_value)
print("As Float:", float_value)
print("As Boolean:", bool_value)

"""#10.Write code to demonstrate type casting with list elements.

"""

# List with string numbers
numbers = ["10", "20", "30"]

print("Original list:", numbers)

# Convert each string to integer
int_list = []
for n in numbers:
    int_list.append(int(n))   # string -> int

print("List after converting to int:", int_list)

# Convert each integer to float
float_list = []
for n in int_list:
    float_list.append(float(n))   # int -> float

print("List after converting to float:", float_list)

"""#11. Write a program that checks if a number is positive, negative, or zero.

"""

num = 15   # value added

if num > 0:
    print("The number is Positive.")
elif num < 0:
    print("The number is Negative.")
else:
    print("The number is Zero.")

num = -8   # value added

if num > 0:
    print("The number is Positive.")
elif num < 0:
    print("The number is Negative.")
else:
    print("The number is Zero.")

num = 0   # value added

if num > 0:
    print("The number is Positive.")
elif num < 0:
    print("The number is Negative.")
else:
    print("The number is Zero.")

"""#12.Write a for loop to print numbers from 1 to 10.

"""

for num in range(1, 10 + 1):   # value added
    print(num)

for num in range(1, 5 + 1):   # value added
    print(num)

for num in range(1, 15 + 1):   # value added
    print(num)

"""#13.Write a Python program to find the sum of all even numbers between 1 and 50.

"""

# Program to find the sum of all even numbers between 1 and 50

total_sum = 0   # value added (starting sum)

for num in range(1, 50 + 1):   # loop from 1 to 50
    if num % 2 == 0:           # check even number
        total_sum += num       # add to sum

print("Sum of all even numbers between 1 and 50 is:", total_sum)

"""#14.Write a program to reverse a string using a while loop."""

# Program to reverse a string using a while loop

text = "Hello World"     # value added
reverse_text = ""        # empty string to store reverse
index = len(text) - 1    # starting from last index

while index >= 0:
    reverse_text += text[index]   # add last character
    index -= 1                    # move backward

print("Original String:", text)
print("Reversed String:", reverse_text)

"""#15.Write a Python program to calculate the factorial of a number provided by the user using a while loop"""

# Program to calculate factorial of a number using while loop

num = 5              # value added (user number)
factorial = 1        # starting value
i = num              # loop starts from num

while i > 0:
    factorial = factorial * i   # multiply
    i = i - 1                   # move backwards

print("The factorial of", num, "is:", factorial)

